### ISSUE TITLE
apply_to filter only in prod environment not working

### ISSUE THREAD

**Issue by layanto** [symfony/assetic-bundle#213]
I can't get apply_to filters to only take effect in prod environment but not in dev environment. What I want to achieve is in prod environment, all js and css are minified (via apply_to filters) and combined while in dev environment, all js and css are not minified and not combined.

With the following configuration, in prod environment, js and css are combined but NOT minified (incorrect behaviour). In dev environment, js and css are not combined and not minified (correct behaviour).

config.yml: no configuration for assetic

config_dev.yml:
```yml
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
```

config_prod.yml:
```yaml
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        catchamonkey_cssmin:
            resource: "%kernel.root_dir%/../vendor/catchamonkey/assetic-filter-bundle/Catchamonkey/Bundle/AsseticFilterBundle/Resources/config/services.xml"
            apply_to: "\.css$"
        jsmin:
            apply_to: "\.js$"
```

I know the filters are working, if I remove assetic configuration from config_dev.yml and move all the assetic configuration from config_prod.yml to config.yml

config.yml:
```yaml
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        catchamonkey_cssmin:
            resource: "%kernel.root_dir%/../vendor/catchamonkey/assetic-filter-bundle/Catchamonkey/Bundle/AsseticFilterBundle/Resources/config/services.xml"
            apply_to: "\.css$"
        jsmin:
            apply_to: "\.js$"
```

With this configuration, in prod environment, all js and css are minified and combined. In dev environment, all js and css are minified and not combined. This shows that the apply_to filters work.

Surely it is possible to configure assetic so to minify and combine js/css in prod environment but to not minify and not combine in dev environment?
