### ISSUE TITLE
Less filter doesn't work, works from the command line and command assetic:dump?!

### ISSUE THREAD

**Issue by gremo** [symfony/assetic-bundle#257]
Quick and dirty check, stopping the process (`node <script>`) right after line 246 of [`Process.php`](https://github.com/symfony/Process/blob/master/Process.php#L246):

``` php
$this->process = proc_open($commandline, $descriptors, $this->processPipes->pipes, $this->cwd, $this->env, $this->options);
var_dump($commandline, $this->env); die();
```

Output:

```
string(41) "'/usr/bin/node' '/tmp/assetic_less5LcIFK'"
array(41) {
  ["NODE_PATH"]=>
  string(22) "/usr/lib/node_modules/"
  ["PATH"]=>
  string(28) "/usr/local/bin:/usr/bin:/bin"
```

Assetic configuration:

``` yml
assetic:
    use_controller: false
    node:           /usr/bin/node
    filters:
        less:
            node_paths: [/usr/lib/node_modules/]
```

Less filter does't work. Gives me a generic error "The process has been signaled with signal 11" (inside the CSS file). If I use the same temp file from the shell, running on CentOS 6.4 x64:

```
export NODE_PATH=/usr/lib/node_modules/
node /tmp/assetic_less5LcIFK
```

It works without problems, outputs the actual CSS complied output. Also the command `php app/console assetic:dump` works fine. The problem occurs when executing from the browser, i.e. `www.mydomain.com/app_dev.php/test`
