### ISSUE TITLE
Duplicated files

### ISSUE THREAD

**Issue by sagikazarmark** [symfony/assetic-bundle#386]
I found a very annoying issue. I try to dump assets in production. Assets configured in in the `config.yml` look like this:

``` yaml
assetic:
    debug: "%kernel.debug%"
    use_controller: false
    filters:
        cssrewrite: ~
        cssmin: ~
    assets:
        space_style:
            inputs:
                - %kernel.root_dir%/../web/bundles/app/rs-plugin/css/settings.css
                - %kernel.root_dir%/../web/bundles/app/fonts/streamline-small/styles.css
                - %kernel.root_dir%/../web/bundles/app/fonts/streamline-large/styles.css
                - %kernel.root_dir%/../web/bundles/app/fonts/template/styles.css
                - %kernel.root_dir%/../web/bundles/app/fonts/social/styles.css
                - %kernel.root_dir%/../web/bundles/app/style/reset.css
                - %kernel.root_dir%/../web/bundles/app/style/superfish.css
                - %kernel.root_dir%/../web/bundles/app/style/prettyPhoto.css
                - %kernel.root_dir%/../web/bundles/app/style/jquery.qtip.css
                - %kernel.root_dir%/../web/bundles/app/style/animations.css
                - %kernel.root_dir%/../web/bundles/app/style/odometer-theme-default.css
                - %kernel.root_dir%/../web/bundles/app/style/style.css
                - %kernel.root_dir%/../web/bundles/app/style/responsive.css
                - %kernel.root_dir%/../web/bundles/app/style/overrides.css
                - %kernel.root_dir%/../web/bundles/app/style/custom.css
            combine: true
            filters:
                - cssrewrite
                - cssmin

```

I use it in twig:

``` twig
{% stylesheets '@space_style' %}
<link rel="stylesheet" href="{{ asset_url }}"/>
{% endstylesheets %}
```

I am trying to invoke the following command:
`sf assetic:dump --no-debug --env=prod`

And the output is:

```
17:14:10 [file+] /Users/mark/Projects/Freelance/space/app/../web/assetic/space_style.css
17:14:10 [file+] /Users/mark/Projects/Freelance/space/app/../web/css/244f47a.css
```

It generates the asset correctly in the default assetic path, and it generates a second asset which is actually being used in the template. `use_controller` is turned off.

What is this second file? Why is it there? It is very annoying.
