### ISSUE TITLE
Error when using multiple guard authenticators

### ISSUE THREAD

**Issue by sudosu** [symfony/assetic-bundle#418]
Hi! I'm using Symfony 3.1 and multiple guard authenticators. Here is my firewalls:
```
firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: ~
            provider: app_user
            form_login:
                login_path: /auth/login
                check_path: /auth/login
                csrf_token_generator: security.csrf.token_manager
            logout:
                path:   /auth/logout
                target: /auth/login
            guard:
                authenticators:
                    - app.email_user_authenticator
                    - app.token_user_authenticator
                    - app.facebook_user_authenticator
                entry_point: app.email_user_authenticator
```

And after installing AsseticBundle I'm getting this error on cache:clear (or composer update):

> [LogicException]
  Unable to register extension "security" as extensions have already been initialized.

Please help me to figure out what is wrong. Thanks.
