### ISSUE TITLE
Coffee filter not filtering by 'apply_to'

### ISSUE THREAD

**Issue by Russellmd** [symfony/assetic-bundle#441]
My configurations:
  "symfony/symfony": "3.3.*",
  "symfony/assetic-bundle": "^2.8"

app/config/config.yml

```
assetic:
    use_controller:
        enabled: "%kernel.debug%"
        profiler: false
    debug: "%kernel.debug%"
    node: /usr/bin/nodejs
    filters:
        cssrewrite: ~
        coffee:
            bin: '%kernel.root_dir%/../node_modules/.bin/coffee'
            apply_to: '\.coffee$'
        uglifyjs2:
            bin: '%kernel.root_dir%/../node_modules/.bin/uglifyjs'
            apply_to: '\.js$'
```

assets.yml
```
assetic:
    assets:
        dashboard_js:
            inputs:
                - table/build/js/TableTableForm.min.js
                - bundles/sw/js/dashboard.js
                - bundles/sw/js/base.coffee
            filters:
                - coffee
                - uglifyjs2
```
in twig file:
```
{% javascripts '@dashboard_js' %}
        <script src="{{ asset_url }}"></script>
    {% endjavascripts %}
```
when I run assetic:dump an exception appear because plain JS files also are filtered by coffee:
```
[Assetic\Exception\FilterException]                                                                                                                                                              
  An error occurred while running:                                                                                                                                                                 
  '/usr/bin/nodejs' '/var/www/html/app/../node_modules/.bin/coffee' '-cp' '/tmp/assetic_coffeeJPz2ai'                                                                                              
  Error Output:                                                                                                                                                                                    
  /tmp/assetic_coffeeJPz2ai:1:1: error: reserved word 'var'
```

The only way I found to exclude these errors is to separate coffee and plain JS assets, something like this:

assets.yml
```
assetic:
    assets:
        dashboard_js:
            inputs:
                - table/build/js/TableTableForm.min.js
                - bundles/moodcountdashboard/js/dashboard-router.js
                - "@base_coffee"
            filters:
                - uglifyjs2

        base_coffee:
            inputs:
                - bundles/moodcountdashboard/js/base.coffee
            filters:
                - coffee
```
