### ISSUE TITLE
404 when loading fonts

### ISSUE THREAD

**Issue by Cypaubr** [symfony/assetic-bundle#446]
Hello,

I use a stylesheet importing some fonts (FontAwesome & Roboto), when accessing the app in dev, all the fonts fail to load (404) and in prod only some fails (404 too).
I tried by adding all font files as assets in the assetic config but it do not solve the issue.
In dev it tries to load fonts from `app_dev.php/fonts/` and `app_dev.php/fonts`.

Here is my assetic configuration :
```yaml
assetic:
    debug: '%kernel.debug%'
    use_controller: '%kernel.debug%'
    #write_to: '%kernel.project_dir%/web/compiled/'
    filters:
        cssrewrite: ~
        uglifyjs2:
            bin: "%kernel.root_dir%/Resources/uglifyjs"
        uglifycss:
            bin: "%kernel.root_dir%/Resources/uglifycss"
```
